[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
crud = "7b3fq4KnprFX3tAiPaS6xspbCPaBbUfdH8kPPoPb1QSb"

[programs.devnet]
crud = "7b3fq4KnprFX3tAiPaS6xspbCPaBbUfdH8kPPoPb1QSb"  # Replace with your program ID if you want to reference it

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"  # Change this to devnet
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
